% % PT VERSION
% % function guiLD(imageTable, outputDir) 
% % % GUILD - Interface gráfica para análise de imagens de Lipid Droplets
% % %
% % %   Visualização interativa com painéis dedicados:
% % %     - Imagem Original
% % %     - Overlays: LDRed, LDGreen, LDColoc, LDDiffuse
% % %     - Terminal de output embutido
% % %     - Botões de Parar e Executar análise estatística em Python
% % %
% % % INPUTS:
% % %   imageTable : tabela com metadados das imagens
% % %   outputDir  : diretório para guardar os resultados
% % %
% % % AUTHOR:
% % %   Ferreira, M. - FCUL-IST, 2025
% % 
% % screenSize = get(0, 'ScreenSize');
% % % GUI Parameters
% % hFig = figure('Name', 'LD Analysis Viewer', 'NumberTitle', 'off', ...
% %     'MenuBar', 'none', 'ToolBar', 'none', ...
% %     'Color', [0.07 0.07 0.07], ...
% %     'Position', screenSize, ...
% %     'Units', 'pixels');
% % 
% % % Store shared handles
% % handles = struct();
% % handles.stopFlag = false;
% % guidata(hFig, handles);
% % 
% % %% Layout Panels
% % 
% % % Top-left: Original Image
% % axOrig = axes('Parent', hFig, 'Units', 'normalized', ...
% %     'Position', [0.05 0.55 0.4 0.4]);
% % title(axOrig, 'Imagem Original', 'Color', 'w');
% % 
% % % Right Panel: LD overlays (Red, Green, Coloc, Diffuse)
% % axOverlay = axes('Parent', hFig, 'Units', 'normalized', ...
% %     'Position', [0.5 0.2 0.45 0.75]);
% % title(axOverlay, 'Overlays LDs', 'Color', 'w');
% % 
% % % Bottom-left: Control Panel
% % uipanelControls = uipanel('Parent', hFig, 'Title', 'Controlo', ...
% %     'FontSize', 10, 'ForegroundColor', 'w', ...
% %     'BackgroundColor', [0.15 0.15 0.15], ...
% %     'Units', 'normalized', 'Position', [0.05 0.05 0.4 0.4]);
% % 
% % % Button: Stop
% % uicontrol(uipanelControls, 'Style', 'pushbutton', ...
% %     'String', '🛑 Parar', ...
% %     'FontSize', 12, 'ForegroundColor', 'w', ...
% %     'BackgroundColor', [0.6 0.2 0.2], ...
% %     'Units', 'normalized', 'Position', [0.1 0.7 0.35 0.2], ...
% %     'Callback', @(~,~) setStopFlag(hFig));
% % 
% % % Button: Executar análise Python
% % % uicontrol(uipanelControls, 'Style', 'pushbutton', ...
% % %     'String', '📊 Análise Estatística (Python)', ...
% % %     'FontSize', 12, 'ForegroundColor', 'w', ...
% % %     'BackgroundColor', [0.2 0.5 0.2], ...
% % %     'Units', 'normalized', 'Position', [0.55 0.7 0.35 0.2], ...
% % %     'Callback', @(~,~) runPythonAnalysis(outputDir));
% % 
% % % Terminal Output
% % txtTerminal = uicontrol(uipanelControls, 'Style', 'edit', ...
% %     'Max', 10, 'Min', 0, ...
% %     'Units', 'normalized', ...
% %     'Position', [0.05 0.05 0.9 0.6], ...
% %     'HorizontalAlignment', 'left', ...
% %     'FontSize', 9, ...
% %     'BackgroundColor', 'black', ...
% %     'ForegroundColor', 'green', ...
% %     'String', 'Terminal de Output...');
% % 
% % %% Iniciar processamento
% % % Chama o pipeline principal com função de flag de interrupção
% % updateTerminal(txtTerminal, '➡️ A iniciar análise ROS...');
% % stopFlagHandle = @( ) getappdata(hFig, 'stopFlag');
% % 
% % mainLD_gui(imageTable, outputDir, axOrig, axOverlay, txtTerminal, stopFlagHandle);
% % 
% % updateTerminal(txtTerminal, '✅ Análise ROS terminada.');
% % end
% 
% 
% % ENG VERSION
% function guiLD(imageTable, outputDir)
% %GUILD - Graphical interface for interactive analysis of Lipid Droplets (LDs).
% %
% %   Features:
% %     - Displays original image and LD overlays (Red, Green, Colocalized, Diffuse)
% %     - Embedded output terminal with live progress updates
% %     - Stop button to interrupt analysis at any moment
% %     - Optional hook for launching post-analysis Python script
% %
% %   INPUTS:
% %       imageTable : table with image metadata and paths
% %       outputDir  : output directory for saving results and reports
% %
% %   AUTHOR:
% %       Prepared for scientific applications by Ferreira, M., FCUL-IST, 2025
% 
% % --------------------- GUI INITIALIZATION ---------------------
% screenSize = get(0, 'ScreenSize');  % Use full screen
% 
% % Create the main GUI window
% hFig = figure('Name', 'LD Analysis Viewer', ...
%               'NumberTitle', 'off', ...
%               'MenuBar', 'none', ...
%               'ToolBar', 'none', ...
%               'Color', [0.07 0.07 0.07], ...
%               'Position', screenSize, ...
%               'Units', 'pixels');
% 
% % Shared handles structure for stop flag, etc.
% handles = struct();
% handles.stopFlag = false;
% guidata(hFig, handles);  % Store it in the figure
% 
% % --------------------- AXES AND PANELS -----------------------
% 
% %% Original Image Display (Top-Left)
% axOrig = axes('Parent', hFig, ...
%               'Units', 'normalized', ...
%               'Position', [0.05 0.55 0.4 0.4]);
% title(axOrig, 'Imagem Original', 'Color', 'w');
% 
% %% Overlay Display (Right Panel)
% axOverlay = axes('Parent', hFig, ...
%                  'Units', 'normalized', ...
%                  'Position', [0.5 0.2 0.45 0.75]);
% title(axOverlay, 'Overlays: LD Red / Green / Colocalized / Diffuse', 'Color', 'w');
% 
% %% Control Panel (Bottom-Left)
% uipanelControls = uipanel('Parent', hFig, ...
%     'Title', 'Controlo', ...
%     'FontSize', 10, ...
%     'ForegroundColor', 'w', ...
%     'BackgroundColor', [0.15 0.15 0.15], ...
%     'Units', 'normalized', ...
%     'Position', [0.05 0.05 0.4 0.4]);
% 
% % --- Stop Button: interrupt long analysis ---
% uicontrol(uipanelControls, 'Style', 'pushbutton', ...
%     'String', '🛑 Parar', ...
%     'FontSize', 12, ...
%     'ForegroundColor', 'w', ...
%     'BackgroundColor', [0.6 0.2 0.2], ...
%     'Units', 'normalized', ...
%     'Position', [0.1 0.7 0.35 0.2], ...
%     'Callback', @(~,~) setStopFlag(hFig));
% 
% % --- Python Post-Analysis Button (optional future use) ---
% % uicontrol(uipanelControls, 'Style', 'pushbutton', ...
% %     'String', '📊 Análise Estatística (Python)', ...
% %     'FontSize', 12, ...
% %     'ForegroundColor', 'w', ...
% %     'BackgroundColor', [0.2 0.5 0.2], ...
% %     'Units', 'normalized', ...
% %     'Position', [0.55 0.7 0.35 0.2], ...
% %     'Callback', @(~,~) runPythonAnalysis(outputDir));
% 
% % --- Terminal Output Window ---
% txtTerminal = uicontrol(uipanelControls, 'Style', 'edit', ...
%     'Max', 10, 'Min', 0, ...  % Multi-line enabled
%     'Units', 'normalized', ...
%     'Position', [0.05 0.05 0.9 0.6], ...
%     'HorizontalAlignment', 'left', ...
%     'FontSize', 9, ...
%     'BackgroundColor', 'black', ...
%     'ForegroundColor', 'green', ...
%     'String', 'Terminal de Output...');
% 
% % --------------------- START ANALYSIS ---------------------
% 
% updateTerminal(txtTerminal, '➡️ Starting LDs analysis...');
% stopFlagHandle = @() getappdata(hFig, 'stopFlag');
% 
% % Launch the main LD analysis pipeline with GUI feedback
% mainLD_gui(imageTable, outputDir, axOrig, axOverlay, txtTerminal, stopFlagHandle);
% 
% updateTerminal(txtTerminal, '✅ LD analysis completed.');
% end


function guiLD(imageTable,outputDir,assetsPath)
%GUILD  Interactive GUI for Lipid Droplet analysis with real‑time overlays.
%
%   AUTHOR:
%       Prepared for scientific use by Ferreira, M., FCUL-IST, 2025

%% ── Main figure --------------------------------------------------------
scr   = get(0,'ScreenSize');
hFig  = figure('Name','LiDRoSIS ‑ LD Viewer', ...
               'NumberTitle','off','MenuBar','none','ToolBar','none', ...
               'Color',[0.08 0.08 0.1],'Position',scr.*[.05 .05 .9 .9]);

%% ── Tabs: Original / Overlays / Metrics --------------------------------
tg = uitabgroup('Parent',hFig,'Position',[0 0.15 1 0.85]);

tabOrig   = uitab(tg,'Title','Original');
tabOver   = uitab(tg,'Title','Overlays');
tabMetric = uitab(tg,'Title','Metrics');

axOrig   = axes('Parent',tabOrig,'Units','normalized','Position',[0 0 1 1]);
axOverlay= axes('Parent',tabOver,'Units','normalized','Position',[0 0 1 1]);
set(axOrig,   'Color', [0.08 0.08 0.10]);   % dark gray background
set(axOverlay,'Color', [0.08 0.08 0.10]);   % same background

txtMetrics = uitable(tabMetric,'Units','normalized','Position',[0 0 1 1]);

%% ── Bottom control panel ----------------------------------------------
pCtrl = uipanel('Parent',hFig,'Units','normalized', ...
    'Position',[0 0 1 0.15],'BackgroundColor',[0.12 0.12 0.15]);

btnStop  = uicontrol(pCtrl,'Style','pushbutton','String','🛑 Stop', ...
    'Units','normalized','Position',[0.02 0.3 0.08 0.4], ...
    'FontSize',12,'BackgroundColor',[0.6 0.2 0.2],'ForegroundColor','w');

btnPy    = uicontrol(pCtrl,'Style','pushbutton','String','📊 Python', ...
    'TooltipString','Run external Python stats','Enable','off', ...
    'Units','normalized','Position',[0.12 0.3 0.08 0.4], ...
    'FontSize',12,'BackgroundColor',[0.2 0.5 0.2],'ForegroundColor','w');

progText = uicontrol(pCtrl,'Style','text','String','Progress: 0/0', ...
    'Units','normalized','Position',[0.22 0.35 0.15 0.3], ...
    'BackgroundColor','none','ForegroundColor','w','FontSize',11);

txtTerm  = uicontrol(pCtrl,'Style','edit','Max',20,'Min',0, ...
    'Units','normalized','Position',[0.39 0.05 0.6 0.9], ...
    'BackgroundColor','black','ForegroundColor',[0.3 1 0.3], ...
    'FontName','Courier New','FontSize',9);

%% ── Stop‑flag handle ---------------------------------------------------
setappdata(hFig,'stopFlag',false);
btnStop.Callback = @(~,~) setappdata(hFig,'stopFlag',true);
stopFlagHandle   = @() getappdata(hFig,'stopFlag');

%% ── Run main analysis --------------------------------------------------
updateTerminal(txtTerm,'➡️  Starting Lipid Droplet analysis...');
mainLD_gui(imageTable,outputDir,axOrig,axOverlay,txtTerm,stopFlagHandle,progText,txtMetrics);
updateTerminal(txtTerm,'✅  LD analysis completed.');
btnPy.Enable='on';
end

